export const CREATE_PERSON = "CREATE_PERSON";
export const RETRIEVE_PEOPLE = "RETRIEVE_PEOPLE";
export const UPDATE_PERSON = "UPDATE_PERSON";
export const DELETE_PERSON = "DELETE_PERSON";
export const ERROR = "ERROR";